name: Use GitHub Secrets

on: [push]

jobs:
  print_secret:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print Secret Value
      run: echo "The secret value is ${{ secrets.GITHUB_REPO }}"
